### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by rodney757**

### CODE REVIEW

**Comment by vsimetka** [comment]
Sorry @rodney757 could you fix the PR? I'll merge once it passes netlify deploy.

**Comment by rodney757** [comment]
can you tell me what the failure is? I can't see the netlify details, can be merged w/o conflicts, and appears to be working correctly locally

**Comment by vsimetka** [comment]
```

ERROR in ./js/blockchain/Network.js

/opt/build/repo/dapp/js/blockchain/Network.js
32:1 error Exporting mutable 'let' binding, use 'const' instead import/no-mutable-exports
32:23 error A space is required after '[' computed-property-spacing
32:25 error A space is required before ']' computed-property-spacing
35:3 error Expected indentation of 4 spaces but found 2 indent
36:5 error Expected indentation of 6 spaces but found 4 indent
36:5 warning Unexpected console statement no-console
37:5 error Expected indentation of 6 spaces but found 4 indent
37:11 error Missing semicolon semi
41:3 error Expected indentation of 4 spaces but found 2 indent
42:5 error Expected indentation of 6 spaces but found 4 indent
42:5 error Assignment to function parameter 'networkID' no-param-reassign
44:1 error Trailing spaces not allowed no-trailing-spaces
45:3 error Expected indentation of 4 spaces but found 2 indent

✖ 13 problems (12 errors, 1 warning)
```

I guess this is because you don't have linter configured properly?

**Comment by rodney757** [comment]
okay, got the linter working :)

**Comment by vsimetka** [comment]
Perfect! I will check and merge tomorrow.

**Pull request merged**
