### PR TITLE
Feature/network status

### PR DESCRIPTION
**Pull request by kkx**
related to showing block number
tested with local geth, worked.
with https://giveth.psdev.io:8545/" the eth.isSyncing is not responding, so it is "synced"

### CODE REVIEW

**Comment by kkx** [comment]
https://trello.com/c/7LdotWc9/39-in-the-right-side-of-menu-show-1-which-network-is-user-connected-to-2-what-block-out-of-total-blocks-is-he-at

**Comment by p-s-dev** [comment]
Is should be responding with false like this:

    $ curl -X POST -H "Content-Type: application/json" -d '[{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}]' https://giveth.psdev.io:8545

    [{"jsonrpc":"2.0","result":false,"id":1}]

**Comment by kkx** [comment]
this should work, change to getSyncing since this method exists in both environment

**Comment by vsimetka** [comment]
I like it, should do some more styling but I think it serves the purpose for now :).

**Pull request merged**
